/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminQuestsRouteImport } from './routes/admin.quests'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as AdminXpRouteImport } from './routes/admin.xp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestsRoute = AdminQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminXpRoute = AdminXpRouteImport.update({
  id: '/xp',
  path: '/xp',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/challenge': typeof ChallengeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quest': typeof QuestRoute
  '/rules': typeof RulesRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/xp': typeof AdminXpRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenge': typeof ChallengeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quest': typeof QuestRoute
  '/rules': typeof RulesRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/xp': typeof AdminXpRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/challenge': typeof ChallengeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quest': typeof QuestRoute
  '/rules': typeof RulesRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/xp': typeof AdminXpRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/challenge'
    | '/leaderboard'
    | '/quest'
    | '/rules'
    | '/admin/participants'
    | '/admin/quests'
    | '/admin/rules'
    | '/admin/themes'
    | '/admin/xp'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/challenge'
    | '/leaderboard'
    | '/quest'
    | '/rules'
    | '/admin/participants'
    | '/admin/quests'
    | '/admin/rules'
    | '/admin/themes'
    | '/admin/xp'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/challenge'
    | '/leaderboard'
    | '/quest'
    | '/rules'
    | '/admin/participants'
    | '/admin/quests'
    | '/admin/rules'
    | '/admin/themes'
    | '/admin/xp'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChallengeRoute: typeof ChallengeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  QuestRoute: typeof QuestRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quests': {
      id: '/admin/quests'
      path: '/quests'
      fullPath: '/admin/quests'
      preLoaderRoute: typeof AdminQuestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/xp': {
      id: '/admin/xp'
      path: '/xp'
      fullPath: '/admin/xp'
      preLoaderRoute: typeof AdminXpRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminQuestsRoute: typeof AdminQuestsRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminXpRoute: typeof AdminXpRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminQuestsRoute: AdminQuestsRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminXpRoute: AdminXpRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChallengeRoute: ChallengeRoute,
  LeaderboardRoute: LeaderboardRoute,
  QuestRoute: QuestRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
